name = "ProblemSets"
uuid = "55e3fc5a-415a-49aa-b08a-13f5b2ba4882"
authors = ["kagalenko-m-b <16374215+kagalenko-m-b@users.noreply.github.com>"]
version = "0.10"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
MacroTools = "0.5"
julia = "1.9"

